repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [--strict]
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
    -   id: markdownlint
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
