name: Upload Docs

on:
  workflow_dispatch:
  pull_request:


jobs:
  publish-docs:
      name: Publish docs
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3
        - name: Publish documentation
          uses: canonical/upload-charm-docs@stable
          id: publishDocumentation
          with:
            discourse_host: discourse.charmhub.io
            discourse_api_username: ${{ secrets.DISCOURSE_API_USERNAME }}
            discourse_api_key: ${{ secrets.DISCOURSE_API_KEY }}
            dry_run: true
